version: '3'
services:
  mongo:
    image: mongo
    volumes:
      - ./init-db.js:/docker-entrypoint-initdb.d/init-db.js:ro
    extra_hosts:
      - "backend:150.0.2.6"
      - "web:150.0.1.6"
    networks:
      db:
        ipv4_address: 150.0.3.6

networks:
  db:
    driver: ipvlan
    ipam:
      driver: default
      config:
        - subnet: 150.0.3.0/24
    driver_opts:
      ipvlan_mode: l2
      parent: eth1
